apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskpulse-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/Harshitraiii2005/TaskPulse'
    targetRevision: HEAD
    path: deployment  

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: taskpulse-namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
