apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskpulse-ingress
  namespace: taskpulse-namespace
spec:
  ingressClassName: nginx
  rules:
    - host: ec2-35-154-147-201.ap-south-1.compute.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskpulse-service
                port:
                  number: 5000
