apiVersion: v1
kind: Service
metadata:
  name: taskpulse-service
  namespace: taskpulse-namespace
spec:
  selector:
    app: taskpulse-app
  type: NodePort  # Exposes the service externally
  ports:
    - port: 5000        
      targetPort: 5000  
      nodePort: 30050   
